# Generated by Django 3.1.2 on 2021-01-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('options', models.CharField(max_length=60)),
                ('correct_option', models.CharField(max_length=60)),
                ('quiz', models.CharField(max_length=60)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
