# Generated by Django 3.1.2 on 2021-01-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='quiz',
        ),
        migrations.AddField(
            model_name='questions',
            name='quizF',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='questions',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
