# Generated by Django 3.1.2 on 2021-02-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20210115_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='quizF',
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.quiz'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
